### PR TITLE
Fixes #442, proxyMiddleware usage

### LINKED ISSUE #442: module.exports proxyMiddelware throw Error
Hello,

I just update your great generator but my usually settings throw now an error:
/project/gulpfile.js:24
  require('./gulp/' + file)(options);
                           ^
TypeError: object is not a function
    at /project/gulpfile.js:24:28
    at Array.map (native)
    at Object.<anonymous> (/project/gulpfile.js:23:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/local/share/npm/lib/node_modules/gulp/bin/gulp.js:108:3)

In gulp/proxy.js, module.exports = [proxyMiddleware];

### PR DESCRIPTION
**Pull request by andyperlitch**
This is in response to changes brought on by #335.

### CODE REVIEW

**Comment by Swiip** [comment]
Needs to test myself but seems great!

**Comment by ronaldallanmojica** [comment]
I have tested this but still no good.. 

i use another module , proxy-middleware  and added few tweaks..

**Comment by hutufeia2009** [comment]
@ronaldallanmojica Can you tell me how to fix?

**Comment by ronaldallanmojica** [comment]
Hi! 
First I installed proxy-middleware:
var proxy = require('proxy-middleware');
var util = require('util');

Then I added this two code at the top of browsersync configuration

    var proxyOptions = url.parse('http://localhost/rest');
    proxyOptions.route = '/api';

    server.middleware = [proxy(proxyOptions)];
    browserSync.instance = browserSync.init({
      startPath: '/',
      server: server,
      browser: browser
    });

**Comment by jossemarGT** [comment]
@andyperlitch hello! Which version of node are you using?

**Comment by Swiip** [comment]
Don't spend too much effort here, #499 will change the problem. I'm interesting if someone could test the proxy on this branch...

**Comment by andyperlitch** [comment]
@jossemarGT I am using 0.12.0. @Swiip I have tested this myself and it appears to work fine. Here is my proxy.js file (with template comments removed and my own comments added):

```js
 /*jshint unused:false */

'use strict';

var httpProxy = require('http-proxy');
var chalk = require('chalk');


module.exports = function(options) {
  // the server I want to proxy to is running here:
  var proxyTarget = 'http://localhost:3390/';

  var proxy = httpProxy.createProxyServer({
    target: proxyTarget
  });

  proxy.on('error', function(error, req, res) {
    res.writeHead(500, {
      'Content-Type': 'text/plain'
    });

    console.error(chalk.red('[Proxy]'), error);
  });

  function proxyMiddleware(req, res, next) {
    // simply proxying api calls to my server
    if (req.url.indexOf('/ws/') === 0) {
      proxy.web(req, res);
    } else {
      next();
    }
  }

  // activating the middleware here 
  return [proxyMiddleware];
};
```

Everything is working fine.

**Comment by zckrs** [comment]
Please @andyperlitch can you rebase ?

**Comment by jossemarGT** [comment]
Thanks @andyperlitch :+1: but I give up... every single request returns 404. I don't know a good way to debug it, more than `console.log` when the `proxy.web` was call.

**Comment by jossemarGT** [comment]
Thanks @andyperlitch :+1: I just needed to add `changeOrigin: true` to your script in the proxy server creation.

```javascript
var proxy = httpProxy.createProxyServer({
  target: proxyTarget,
  changeOrigin: true
});
```

Hope to help somebody else with that 'cuz this issue got my nerve :cry:

**Comment by andyperlitch** [comment]
@jossemarGT alright! glad i could help. @zckrs I'll try and rebase and update.

**Comment by andyperlitch** [comment]
@zckrs: looks like @Swiip made changes that again move away from having all gulp subfiles export functions, so yeaa.... im thinking of closing this out. Thoughts?

**Comment by jossemarGT** [comment]
How about leaving your fork alive and let me to apply your changes from new fork?

**Pull request closed without merging**
