### PR TITLE
Add Material-Icons for Angular-Material && fix dynamic path to bower_components

### LINKED ISSUE #716: Google material icons
Hi, how can i use google material icons? http://google.github.io/material-design-icons/#getting-icons

I am using sass in my project and i don't find a way to use them. 
i tried with bower and npm but nothing.,,
Any help would be really kind.

### PR DESCRIPTION
**Pull request by zckrs**
fix #716

### CODE REVIEW

**Comment by Swiip** [comment]
:+1:

**Comment by damdoum** [comment]
:clap: :+1:

**Comment by mackelito** [comment]
Just a question.. why not using the original git repo?
http://github.com/google/material-design-icons/

**Comment by zckrs** [comment]
Too many MB. We need only iconfonts https://github.com/google/material-design-icons/tree/master/iconfont

**Comment by mackelito** [comment]
Sure.. but now we are using https://github.com/zckrs/material-design-iconfont ?
Why I´m asking is because when trying to use the "shopping cart" icon I get the wrong icon.. so my guess is that the docs on http://google.github.io/material-design-icons/#icon-font-for-the-web is not valid for this package?

even if there are things we dont need perhaps it better to use the original source?.. we still can choose to only include what is needed to the site being built :)

**Pull request merged**
