### PR TITLE
Fix for bugs #909 and #660

### PR DESCRIPTION
**Pull request by GitAngel**
1. Added possibility of reloading page as soon as `index.html` file changes.
2. Updated previous PR with the possibility of reloading **only** styles (css) when they are being changed instead of full reload of the page

### CODE REVIEW

**Comment by Swiip** [comment]
Seems great to me. Unlike the other time I'll take the time to perform some manual tests!

**Comment by GitAngel** [comment]
@Swiip Yes, this time I did manually testing myself as well. Tried to use generator with `yeoman` and it was working for me as intended. Hope, for you it will be the same.
Good luck, Matthieu ;)

**Comment by alfaproject** [comment]
`browserSync.reload({ stream: true })` is deprecated by the way.
You should use `browserSync.stream()`: http://www.browsersync.io/docs/api/#api-stream

**Comment by Swiip** [comment]
Thanks @alfaproject

**Comment by GitAngel** [comment]
Haha) No luck for me)
I will remake PR this evening with `browserSync.stream()`. Thank you, @alfaproject .

**Comment by GitAngel** [comment]
After searching in Internet for quite long:
1. I didn't find any mentioning that `browserSync.reload({ stream: true })` is deprecated (yes, I've seen messages where people recommend to use `browserSync.stream()` but no words about deprecation).
2. `browserSync.stream()` requires filter as an additional parameter (something like: `browserSync.stream('*.css')`) and this is not the best concept from my point of view as far as we are hardcoding `css` value one more time. For example, if the user would like to compile his files not into `.css` but into `.mycss` reload of the browser won't work anymore. For sure, this situation might never happen but still I'm not a big fan of hardcoding values...

**Comment by Swiip** [comment]
stream() should be just a shortcut. You don't have to pass an argument because it returns a Node stream and it will trigger reloads in BS only for the files he found in the stream.

**Comment by Swiip** [comment]
Perfect! :+1:

**Comment by alfaproject** [comment]
@GitAngel I realize that, but the reload with stream option is not even documented anymore, that's why I mentioned it. I guess new people would be like, which kind of magic is this? (:

**Comment by GitAngel** [comment]
@alfaproject Yes, I absolutely agree with you. It's a good idea to be always up-to-date. Thank you for info ;)

**Comment by Swiip** [comment]
:+1: Thanks a lot.

**Comment by GitAngel** [comment]
Great) Thank you ;)

**Pull request merged**
