### PR TITLE
fix coffee test auto task

### LINKED ISSUE #438: gulp test:auto not watching for changes
Hello,

the task "test:auto" is not watching for file change, the Karma option autoWatch must be set to true to do so.

Here's what I put in gulp/unit-tests.js to get it working:

`karma.server.start({
        configFile: __dirname + '/../karma.conf.js',
        files: files,
        autoWatch: !singleRun,
        singleRun: singleRun
      }, done);`

### PR DESCRIPTION
**Pull request by tb**

### CODE REVIEW

**Comment by zckrs** [comment]
At moment, we don't support "natively" test file written with jsPreproc

**Comment by Swiip** [comment]
I have to test unit tests in js preprocessed file with the last update of the karma workflow.

But what's certain is that I want the coffee processing in gulp and not in karma. I want the configuration centralized in gulp and not split up in other tools.

**Comment by tb** [comment]
Is the centralized processing producing .js files for only the changed files? I.e. I change some.spec.coffee and only some.spec.js is generated?

**Comment by zckrs** [comment]
Outdated sorry

**Pull request closed without merging**
