### PR TITLE
depend on bootstrap-sass instead of bootstrap-sass-official

### PR DESCRIPTION
**Pull request by nanocom**
the bootstrap-sass-official repo has been renamed

### CODE REVIEW

**Comment by Swiip** [comment]
Great but not complete. Try searching for `bootstrap-sass-official` in the whole project, there is references in node sources and tests.

**Comment by nanocom** [comment]
yes will do

**Comment by nanocom** [comment]
done

**Comment by zckrs** [comment]
Merged bbdb6d2dbe1ad829fbcc3b7b7bc9fa23a8921683 thank you

**Pull request closed without merging**
