### PR TITLE
Add Angular New Router

### PR DESCRIPTION
**Pull request by Swiip**
https://github.com/angular/router

The lib is still experimental but it allows to try it easily. Seems to work pretty well. TSLint cry because there is no typings but for the rest it's ok.

As usual, I push early code to get remarks and do the tests after.

### CODE REVIEW

**Comment by Swiip** [comment]
Done.

I also added 2 npm commands I often use while developping and was tired of retyping them every time.

**Comment by hadimichael** [comment]
+1 for this. Any idea when it will be merged in?

**Comment by Swiip** [comment]
I was waiting for @zckrs to come back from holliday for a review. Nothing stop this apart from that I think.

**Comment by hadimichael** [comment]
I cloned the repo and merged the branch in locally. I can confirm that it's working nicely for me. :+1:

**Comment by sdornan** [comment]
Shouldn't the router as it exists in the Angular 2 repo be used instead?

From angular/router readme:
```
For now, the code has been moved to angular/angular. APIs are still rapidly changing, so I don't recommend using this in an important production app quite yet.
```

I think this is it? https://github.com/angular/angular/tree/master/modules/angular1_router

**Comment by zckrs** [comment]
:+1:

**Pull request merged**
