### PR TITLE
update angular material version to 1.0.0

### PR DESCRIPTION
**Pull request by pi-jzl**

### CODE REVIEW

**Comment by Swiip** [comment]
Did you check that there is no regression by updating the version?

**Comment by zckrs** [comment]
Lastest version is v1.0.0-rc4

**Comment by Swiip** [comment]
Better wait the 1.0.0 final, it should be soon now.

**Comment by sarunast** [comment]
v1 is out now.

**Comment by designnotdrum** [comment]
+1, please merge. v1.0.5 now.

**Comment by Swiip** [comment]
:+1:

**Comment by designnotdrum** [comment]
holla. thanks @Swiip

**Pull request merged**
