### PR TITLE
[JS] Apply angular-styleguide by John Papa

### LINKED ISSUE #440: Provide option to use John Papa's style guide
The style guide provided by John Papa (https://github.com/johnpapa/angular-styleguide) is used by a number of people in the community and based on the fact that the angular team is working with John Papa to support the style guide going forward, it would be nice if the generator supported the standards in the style guide.  Both in the examples provided and in the JSHint files.

### PR DESCRIPTION
**Pull request by zckrs**
Based on https://github.com/johnpapa/angular-styleguide/

#### Single Responsibility
* [x] [Style [Y001](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y001)]

#### IIFE
* [x] [Style [Y010](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y010)] 91508b11247ea7c3413eaeb8a18a2d36f60e95ff

#### Modules
* [ ] [Style [Y020](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y020)] not yet illustrated
* [x] [Style [Y021](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y021)]
* [x] [Style [Y022](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y022)]
* [x] [Style [Y023](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y023)]
* [x] [Style [Y024](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y024)] 0b3efd1fefb8449e15bfde1ce4857992ae59a4a4

#### Controllers
* [x] [Style [Y030](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y030)] ccc5c776c136435bc6bda452c32cc555e4f20d9f
* [x] [Style [Y031](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y031)] ccc5c776c136435bc6bda452c32cc555e4f20d9f
* [x] [Style [Y032](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y032)] ccc5c776c136435bc6bda452c32cc555e4f20d9f
* [ ] [Style [Y033](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y033)] not yet illustrated
* [ ] [Style [Y034](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y034)] not yet illustrated
* [ ] [Style [Y035](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y035)] not yet illustrated
* [x] [Style [Y037](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y037)]
* [x] [Style [Y038](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y038)] 3199f8857899b7d00fb5fe1ce7b31a890d7e721e

#### Services
* [ ] [Style [Y040](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y040)] services not yet illustrated 

#### Factories
* [ ] [Style [Y050](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y050)] factories not yet illustrated 

* [ ] [Style [Y051](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y051)] factories not yet illustrated
* [ ] [Style [Y052](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y052)] factories not yet illustrated
* [ ] [Style [Y053](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y053)] factories not yet illustrated

#### Data Services
* [ ] [Style [Y060](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y060)] data services not yet illustrated
* [ ] [Style [Y061](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y061)] data services not yet illustrated

#### Directives
* [ ] [Style [Y070](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y070)] directives not yet illustrated
* [ ] [Style [Y072](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y072)] directives not yet illustrated
* [ ] [Style [Y073](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y073)] directives not yet illustrated
* [ ] [Style [Y074](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y074)] directives not yet illustrated
* [ ] [Style [Y075](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y075)] directives not yet illustrated
* [ ] [Style [Y076](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y076)] directives not yet illustrated

#### Resolving Promises for a Controller
* [ ] [Style [Y080](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y080)] resolving promises not yet illustrated
* [ ] [Style [Y081](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y081)] resolving promises not yet illustrated

#### Manual Annotating for Dependency Injection
* [x] [Style [Y090](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y090)] we don't manually identify dependencies, we use ng-annotate
* [x] [Style [Y091](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y091)] we don't manually identify dependencies,  we use ng-annotate
* [ ] [Style [Y092](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y092)] router resolver not yet illustrated

#### Minification and Annotation
* [x] [Style [Y100](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y100)] 45432ec347b4d0947f1a14d9834ea018b5b0c569
* [x] [Style [Y101](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y101)]

#### Exception Handling
* [ ] [Style [Y110](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y110)] exception handling not yet illustrated
* [ ] [Style [Y111](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y111)] exception handling not yet illustrated
* [ ] [Style [Y112](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y112)] exception handling not yet illustrated

#### Naming
* [x] [Style [Y120](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y120)]
* [x] [Style [Y121](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y121)]
* [x] [Style [Y122](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y122)]
* [x] [Style [Y123](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y123)]
* [x] [Style [Y124](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y124)] d8fd378
* [ ] [Style [Y125](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y125)] factories not yet illustrated
* [ ] [Style [Y126](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y126)] directives not yet illustrated
* [x] [Style [Y127](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y127)] b9c45a2
* [ ] [Style [Y128](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y128)] configuration file not yet illustrated
* [ ] [Style [Y129](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y129)] route file not yet illustrated

#### LIFT Principle
* [x] [Style [Y140](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y140)]
* [x] [Style [Y141](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y141)]
* [x] [Style [Y142](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y142)]
* [x] [Style [Y143](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y143)]
* [x] [Style [Y144](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y144)]

#### Application Structure
* [x] [Style [Y150](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y150)]
* [ ] [Style [Y151](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y151)] layout not yet illustrated
* [x] [Style [Y152](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y152)]

#### Modularity
* [ ] [Style [Y160](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y160)] not illustrated
* [ ] [Style [Y161](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y161)] not illustrated
* [ ] [Style [Y162](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y162)] not illustrated
* [ ] [Style [Y163](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y163)] not illustrated
* [ ] [Style [Y164](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y164)] not illustrated
* [ ] [Style [Y165](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y165)] not illustrated

#### Startup Logic
* [ ] [Style [Y170](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y170)] configuration not yet illustrated
* [ ] [Style [Y171](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y171)] run not yet illustrated

#### Angular $ Wrapper Services
* [ ] [Style [Y180](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y180)] not yet illustrated
* [ ] [Style [Y181](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y181)] not yet illustrated

#### Testing
* [ ] [Style [Y190](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y190)]
* [ ] [Style [Y191](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y191)]
* [x] [Style [Y192](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y192)]
* [ ] [Style [Y193](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y193)]
* [x] [Style [Y194](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y194)]
* [ ] [Style [Y195](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y195)]
* [ ] [Style [Y196](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y196)]
* [ ] [Style [Y197](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y197)]

#### Animations
* [ ] [Style [Y210](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y210)] not yet illustrated
* [ ] [Style [Y211](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y211)] not yet illustrated
* [ ] [Style [Y212](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y212)] not yet illustrated

#### jsDoc
* [ ] [Style [Y220](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y220)] not implemented

#### JS Hint
* [x] [Style [Y230](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y230)]

#### JSCS
* [ ] [Style [Y235](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y235)] not yet implemented

#### Constants
* [ ] [Style [Y240](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y240)] not illustrated
* [ ] [Style [Y241](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y241)] not illustrated

#### File Templates and Snippets
* [ ] [Style [Y250](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y250)] add a link in our README ?
* [ ] [Style [Y251](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y251)] add a link in our README ?
* [ ] [Style [Y252](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y252)] add a link in our README ?
* [ ] [Style [Y253](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y253)] add a link in our README ?
* [ ] [Style [Y254](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y254)] add a link in our README ?

#### Yeoman Generator
* [ ] [Style [Y260](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y260)] Create a PR to add this generator ? 

#### Routing
* [x] [Style [Y270](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y270)] AngularUI Router is the first default choice
* [x] [Style [Y271](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y271)]

#### Task Automation
* [x] [Style [Y400](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y400)] 8dcc39f

#### Filters
* [ ] [Style [Y420](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y420)] not yet illustrated

***
close #440

### CODE REVIEW

**Comment by robertbaker** [comment]
+1

**Comment by robertbaker** [comment]
Anxiously awaiting the completion of this. I have already changed my js files to use IFE and named functions and controllerAs.

**Comment by zckrs** [comment]
Roadmap of next features illustrated:
1- directives
2- factories/services/data services
3- module/layout

Others
- filter
- configuration/route
- runBlock/constants

**Comment by zckrs** [comment]
Maybe we should merge this PR and create a new for each feature

**Comment by zckrs** [comment]
@Swiip I will continue in another PR to add feature

**Comment by zckrs** [comment]
I have test with many differents configurations. I think you can merge @Swiip :smile:

**Comment by Swiip** [comment]
:+1:

**Comment by zckrs** [comment]
# What is left ?

#### Routing resolve too heavy for a generated app
* [Style [Y081](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y081)] Route Resolve Promises 
* [Style [Y092](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y092)] use @ngInject for route resolve

#### Multiple modules too heavy for a generated app
* [Style [Y020](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y020)] Avoid naming collisions submodule not illustrated
* [Style [Y151](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y151)] Layout not illustrated
* [Style [Y160](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y160)] Modularity not illustrated
* [Style [Y161](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y161)] Modularity not illustrated
* [Style [Y162](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y162)] Modularity not illustrated
* [Style [Y163](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y163)] Modularity not illustrated
* [Style [Y164](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y164)] Modularity not illustrated
* [Style [Y165](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y020)] Modularity not illustrated
* [Style [Y241](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y241)] Constants submodule not illustrated

#### Tests are present but coverage != 100%
* [Style [Y190](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y190)] Testing
* [Style [Y191](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y191)] Testing
* [Style [Y193](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y193)] Testing
* [Style [Y195](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y195)] Testing
* [Style [Y196](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y196)] Testing
* [Style [Y197](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y197)] Testing

#### Planned 
* [Style [Y220](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y220)]  jsDoc not  yet implemented
* [Style [Y235](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y235)] JSCS not yet implemented

****
If @johnpapa has little time, a lighting review would be much appreciated. :smiley:

**Pull request merged**
