### PR TITLE
Update del usage with promise

### PR DESCRIPTION
**Pull request by zckrs**

### CODE REVIEW

**Comment by MrBuBBLs** [comment]
This fixes an issue with the 2.x version of the ```del``` module and looks good as is.
But why use the callback when you can just 'return' it to fullfill the promise ?

As illustrated there : https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md

In JS:
```javascript
return $.del([path.join(conf.paths.dist, '/'), path.join(conf.paths.tmp, '/')]);
```

**Comment by zckrs** [comment]
Nice catch. Thank you.

**Comment by Swiip** [comment]
:+1:

**Comment by MrBuBBLs** [comment]
@zckrs You're welcome :)

**Pull request merged**
