### PR TITLE
Add HTML Preprocessors (Jade, Haml and Handlebars)

### PR DESCRIPTION
**Pull request by Toilal**
This implements HTML preprocessors (template engine).

It supports jade, haml and handlebars through [consolidate](https://www.npmjs.com/package/consolidate). Multiple preprocessors can be supported at the same time, it's based on filename extension in `src/app` or `src/components`.

Still to be done:
- [x] Make unit tests pass.

### CODE REVIEW

**Comment by sebastialonso** [comment]
Hi. I created a project choosing Jade as the preprocessor. 
I created some html views, they work OK. But then I write them into Jade, change the extensions in both the files and the routes in index.coffee, but all get is unparsed Jade text.

Is there something else I need to do to be able to work with Jade?

**Comment by codingrogue** [comment]
Sorry for the dump question but if I choose to use handlebars with angular, can I use it like server-side handlebars? Like access the variables exported with the angular scope? If so, how?

**Comment by Swiip** [comment]
Nop, you can't. Its preprocessed by Gulp and served statically to Angular. Handlebars is the less useful as it keep the "XML like" syntax.

**Comment by malfborger** [comment]
@sebastialonso Got the same issue. Am i missing something? Do you need to configure preprocessing of jade 2 html?

**Comment by Swiip** [comment]
You need to address them with .html in your code. Angular can't load jade templates. Gulp compile them and angular load standard html.

**Pull request merged**
