### PR TITLE
Replace jshint for eslint

### PR DESCRIPTION
**Pull request by Swiip**
Finally #168

### CODE REVIEW

**Comment by Swiip** [comment]
Forgot to mention that it includes https://github.com/Gillespie59/eslint-plugin-angular from @Gillespie59

**Comment by Gillespie59** [comment]
As discussed on Twitter, you change some code ($digest vs $apply), I think after the integration of my plugin. 
But according to this video the $digest method only update the current scope and its children. The $apply method will start the refrest from the $rootScope. So maybe the $digest is more performant than the second one. 

I do not know if it has an impact on your archetype, but if you want I can update my rule, because it check the wrong thing. 

https://egghead.io/lessons/angularjs-apply-vs-digest

Except from that, everything looks good ;)

**Comment by Gillespie59** [comment]
I have publish a 0.4.0 with a fix for this issue. You can update your package.json with this version.

**Comment by Swiip** [comment]
Thanks for your analysis. Will take the new version :)

**Comment by sdornan** [comment]
Looking forward to this one.

**Comment by zckrs** [comment]
:+1: but need rebase with master

**Pull request merged**
