### PR TITLE
upgrade angular-bootstrap to 0.14.2

### LINKED ISSUE #856: ui-bootstrap directive not working util change to use 0.14.x version
hello, while I use generator-gulp-angular 1.0.0 for default settings, I found that it failed for very simple ui-bootstrap directives(see below code), then after upgrading it to 0.14.2 in bower.json, issue resolved. 

    <uib-accordion close-others="true">
      <uib-accordion-group heading="Static Header">
        This content is straight in the template.
      </uib-accordion-group>
    </uib-accordion>

but I am not sure, it is good to simply have this patch:

    diff --git a/app/templates/_bower.json b/app/templates/_bower.json
    index 255a021..36d4ab1 100644
    --- a/app/templates/_bower.json
    +++ b/app/templates/_bower.json
    @@ -49,7 +49,7 @@
         "material-design-lite": "~1.0.4",
         "material-design-iconfont": "~0.0.2",
     <% } if(props.bootstrapComponents.key === 'ui-bootstrap') { -%>
    -    "angular-bootstrap": "~0.13.4",
    +    "angular-bootstrap": "~0.14.2",
     <% } if(props.bootstrapComponents.key === 'angular-strap') { -%>
         "angular-strap": "~2.3.1",
     <% } if(props.foundationComponents.key === 'angular-foundation') { -%>

### PR DESCRIPTION
**Pull request by pluswave**
fix #856.

### CODE REVIEW

**Comment by zckrs** [comment]
Thank you for PR.
Can you confirm any breaking change exist in 0.14.2 ?

**Comment by pluswave** [comment]
I am new to bootstrap and angular-ui-bootstrap. From here: 

  https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md

I now know that #856 should be misunderstood by myself. directives are renamed from 0.14.x , adding uib- prefix but I used the latest doc.

**Comment by pluswave** [comment]
sorry, I am not sure why my new commits are automatically added to this PR. so this is a github default correct ? 

for the new two commits, my idea is (-> means depends)

   build -> inject -> partials
  serve -> inject -> partials

before my commits:

   build -> inject + partials
   serve -> inject

for a real project, I changed partials to "transform html" to generate some code from js templates (via https://github.com/ernestoalejo/gulp-ngbs-forms ) which can be benefit from my two commits.

however this comes to some CI error (3 errors).

two questions:

1. how to test for the CI error locally ?
2. how about the idea behinds the new two commits ?

**Comment by busches** [comment]
Any commits to the same branch as the PR will auto push to the PR. If the commits should not belong, than they need to be on a separate branch. I would split the two new commits into a different branch and thus a different PR.

If you look in https://github.com/Swiip/generator-gulp-angular/blob/master/.travis.yml you can see that other than some prep work the Travis script is simply running `npm test` and you should be able to do some from your computer as well, assuming you're not on Windows.

**Comment by pluswave** [comment]
as #865 is a fake issue, close this now.

**Pull request closed without merging**
