### PR TITLE
Fix inject script for jsPrepro

### PR DESCRIPTION
**Pull request by zckrs**
injectScript only depend if jsPrepro is used
If jsPrepro we use the .tmp folder

### CODE REVIEW

**Comment by Swiip** [comment]
I was considering that when you choose Coffee for example you can still have JS sources, both will work. The change that you make will break this.

What was the problem with the original conf?

**Comment by zckrs** [comment]
The orignal problem is we inject spec.**js** in the `src` folder instead of  `.tmp` folder.

Mixed Coffee and JS is a common case in project ?

**Comment by Swiip** [comment]
Yep, at least it "was"

**Comment by Swiip** [comment]
Is it not possible to keep the possibility excluding the `spec.js` files?

**Comment by zckrs** [comment]
Done

**Comment by Swiip** [comment]
:+1:

**Pull request merged**
