### PR TITLE
Fix for bug #660 (index.html file is incorrectly reloaded)

### PR DESCRIPTION
**Pull request by GitAngel**
Separated logic of reload and compilation for Gulp 3.x allowing to make proper reload for index.html and other assets.
Fix for bug #660

### CODE REVIEW

**Comment by Swiip** [comment]
:+1:

**Comment by alfaproject** [comment]
Editing a SCSS file now will trigger a full page reload, while before it would only update the stylesheet without a full page reload. To be honest, I prefer the old way.

**Comment by Swiip** [comment]
Arg, I've to look deeper...

**Comment by alfaproject** [comment]
For now, I changed the styles reload task to this:

```js
    gulp.task('styles-reload', ['styles'], function() {
        browserSync.reload('*.css');
    });
```

It's hacky as fuck, but gets the job done until I can think of a cleaner solution.

**Comment by Swiip** [comment]
Thanks for sharing.

**Comment by GitAngel** [comment]
Yes, I see. The problem is that now we are calling `browserSync.reload();` without `stream:true` parameter. In the evening I will try to change the process a bit. I got some ideas for this...

**Comment by GitAngel** [comment]
Ok, I've did a new PR: https://github.com/Swiip/generator-gulp-angular/pull/911 which takes into account problem mentioned by @alfaproject . Now, in case of styles changes, reload is being done only to styles themselves instead of full page reload.

**Pull request merged**
