### PR TITLE
Reorder prompts

### PR DESCRIPTION
**Pull request by Swiip**
Especially jQuery 2 and UI Router as default values.

### CODE REVIEW

**Comment by zckrs** [comment]
What do you think to use "default" value in list definition ?
https://github.com/SBoudrias/Inquirer.js#list----type-list-

```
{
    "type": "list",
    "name": "jQuery",
    "message": "Would you need jQuery or perhaps Zepto?",
    "default": 0,
    "choices": [
      {
        "value": {
          "key": "jquery2"
        },
        "name": "jQuery 2.x (new version, lighter, IE9+)"
      },
      {
        "value": {
          "key": "jquery1"
        },
        "name": "jQuery 1.x (branch still supporting IE6, 7 and 8)"
      },
      {
        "value": {
          "key": "zepto"
        },
        "name": "ZeptoJS 1.1.x (jQuery compatible but very much lighter)"
      },
      {
        "value": {
          "key": "none"
        },
        "name": "None (Angular will use its own jqLite)"
      }
    ]
  }
```

**Comment by Swiip** [comment]
What does it change comparing the first line of a list where you have to choose one?

**Comment by zckrs** [comment]
"default" will pre-select in list

**Comment by Swiip** [comment]
Even if I use default value, I like having the default value in first position.

**Comment by zckrs** [comment]
Agree ^__^

**Pull request merged**
