### PR TITLE
Organize bower overrides

### PR DESCRIPTION
**Pull request by Swiip**
By computing them before templating.

Yep, I know, I have to fix tests, and I should write tests while coding...

### CODE REVIEW

**Comment by Swiip** [comment]
Tests done.

I moved wiredep exclusions computing in a new `src/bower.js` file to unite specific bower computing.

**Comment by zckrs** [comment]
:+1:
Nice work but can you rebase on master ?
And why you write this PR ? Bug, improvement ?

**Comment by Swiip** [comment]
You're right, I forgot to explain evil plan for the conquest of the universe.

First of all, it should fix #644 and fix #637 as this code overrides fonts links in the main of bootstrap's bower file.

But more important, I'm working on the angular new router feature and it requires also a bower overrides and I needed this to do it correctly.

**Comment by loren138** [comment]
Any thoughts on the next release?  Trying to decide the best way to get bootstrap fonts working for my code...

**Pull request merged**
