### PR TITLE
Refacto test sample

### PR DESCRIPTION
**Pull request by zckrs**
Rewrite unit test with Karma
* [x] Add test in plain Javascript with 98% coverage 
* [x] Enable coverage report for plain Javascript and Coffescript
* [x] Add sample test in Coffescript
* [ ] Add sample test in ES6 (actually not written in ES6 _main.controller.spec.es6) 
* [ ] Add sample test in Typescript (actually not written in Typescript _main.controller.spec.ts)

***
Coverage report for plain Javascript
coverage-plain-js

### CODE REVIEW

**Comment by zckrs** [comment]
@Swiip I don't understand why last inception test failed with custom path option

`[src:src/angular/app e2e:tests/e2e dist:target/build/folder tmp:.tmp/folder]`

Error is:
`Error: Unexpected request: GET app/components/navbar/navbar.html`

I suspect a problem with karma-ng-html2js-preprocessor and angular $templateCache

Help appreciate :-(

**Comment by Swiip** [comment]
For the templates un karma de use a plugin karmaHtml2Js. Look at the karma conf the path of sources ils hardcoded. Your new tests actually already finds a bug.

**Comment by zckrs** [comment]
:tada:  thank you

**Comment by Swiip** [comment]
:+1: :+1:

**Pull request merged**
