### PR TITLE
gulp-angular-filesort included in ES6 projects

### PR DESCRIPTION
**Pull request by cgaudreau**
Easy enough, figured I'd send a pull request. #369

### CODE REVIEW

**Comment by zckrs** [comment]
Can you add a test for this case ? 
https://github.com/Swiip/generator-gulp-angular/blob/master/test%2Ftemplate%2Ftest-package.js#L112

**Comment by zckrs** [comment]
Can you rebase your branch with master ? We fix travis by ignore fail on iojs.

**Comment by cgaudreau** [comment]
Huh. Not sure why it's failing now.

**Comment by zckrs** [comment]
@Swiip are you agree to merge ?

**Comment by cgaudreau** [comment]
Looks like it's succeeding now. The world is a great place.

**Comment by Swiip** [comment]
Of course :+1: thanks

**Pull request merged**
