### PR TITLE
refactor(gulp): avoid to overload gulp with external options

### PR DESCRIPTION
**Pull request by highfivedenis**
- i just have a doubt about the test `test/test-files-generate.mocha.js` L1041

### CODE REVIEW

**Comment by Swiip** [comment]
A little bothered because it impact all gulp files but it's sure better to not overload the gulp object.

Just to be consistent can you replace lodash's map and filter by the standard ES5?

**Comment by highfivedenis** [comment]
Done, have you look at the test :  ```test/test-files-generate.mocha.js``` L1041

**Comment by Swiip** [comment]
I broke the merge accepting another PR, can you merge please?

**Comment by highfivedenis** [comment]
@Swiip : jobs done

**Comment by Swiip** [comment]
Thanks!

**Comment by zckrs** [comment]
:+1:

**Comment by andyperlitch** [comment]
This broke how `gulp/proxy.js` works completely.

**Pull request merged**
