### PR TITLE
Changed TypeScript index.module classes to functions

### LINKED ISSUE #629: this is undefined in RouterConfig class in TypeScript
Hi, not sure how to report this issue.

I'm using TypeScript pre-processor and wanted to modify the RouterConfig class to make use of methods in order to structure it better. However `this` was undefined in the constructor. I suppose, it is due to the fact, how Angular is calling that class, probably not with `new`. Unfortunately I'm not experienced enough in JavaScript to be 100% sure how things are supposed to work, if they don't.

I've created a [StackOverflow question](http://stackoverflow.com/questions/30978743/how-can-this-be-undefined-in-the-constructor-of-an-angular-config-class) with a detail example:

    class TestConfig {
      constructor() {
        console.log('TestThis =>');
        console.log(this);
        console.log('<= TestThis');
      }
    }
  
    angular.module('todoList', [])
    	.config(TestConfig);

Which logs for me:

    TestThis =>
    undefined
    <= TestThis

I do understand that it's not directly your issue, but I think it's a bit misleading to create it as a class, if it in fact can't be used as one. Or is anything wrong with the code? That might be the case as well, I just couldn't find anything. Controllers and Services work as expected.

Thx for your feedback.

### PR DESCRIPTION
**Pull request by mikesigs**
This fixes #629.

index.ts was split into several files: index.module.ts, index.config.ts, index.route.ts, and index.run.ts. The last three files in that list each defined classes to encapsulate their functionality. However, in the index.module.ts, the classes were being passed to the angular module.config() and module.run(), but Angular doesn't call these functions with the new keyword, meaning they should just be functions. Having them as classes didn't actually break anything, but when trying to use `this` in the constructor, you got `undefined` (in strict mode) or `window` otherwise. Changing these implementations to just `export function` will prevent devs from writing code as though it's a constructor.

### CODE REVIEW

**Comment by zckrs** [comment]
lgtm :+1:

**Comment by zckrs** [comment]
@mikesigs Do you have already written unit test in TypeScript with Karma ? I look for help or a good example.

**Comment by Swiip** [comment]
Just a question, if we change the type from class to function, don't we should change the first character of the name of a lower case.

**Comment by zckrs** [comment]
Agree

**Comment by mikesigs** [comment]
I lower-cased the function names.

@zckrs No, I'm afraid that's not something I've tackled yet. But I agree, there aren't too many great examples out there.

**Comment by zckrs** [comment]
Can you fix your test at https://github.com/Swiip/generator-gulp-angular/blob/master/test/template/test-index-module-js.js#L57 ?

**Comment by mikesigs** [comment]
Thanks zckrs. It's fixed now. Really wish I could get these tests to work locally. Sorry about that.

**Comment by zckrs** [comment]
No problem :-) Travis ensure.
Thank you for contributions.

**Comment by pgrm** [comment]
:+1:

**Pull request merged**
