### PR TITLE
Doc: port change with Browser-Sync

### PR DESCRIPTION
**Pull request by bcldvd**
First thing I wanted to do after generating my app with this generator was to change the port :/
I thought I'd add it for others like me :)

### CODE REVIEW

**Comment by Swiip** [comment]
As said here https://github.com/Swiip/generator-gulp-angular/blob/master/docs/how-it-works.md#gulpconfjs, we are very thrifty about the `conf.js` file as we don't want to come back to a big `json` file like with Grunt.

I don't see why it's needed to deport this conf from `server.js` to `conf.js`. It can be kept in `server.js`.

What we can do is to have better doc about configuring BS. If you turn your PR into a doc update, it would be highly appreciated.

**Comment by bcldvd** [comment]
Changed it into a doc update :)

**Comment by Swiip** [comment]
Thanks :) Would it be to much to ask if you could turn this into something a little more generic about "all" BS options including a link to http://www.browsersync.io/docs/options/ ?

**Comment by zckrs** [comment]
:+1:

**Pull request merged**
