### PR TITLE
change build code to use gulp-filter 3.0

### PR DESCRIPTION
**Pull request by e-oz**
npm module `gulp-filter` version 3.0 has backward-incompatible changes, this commit fixing it

### CODE REVIEW

**Comment by e-oz** [comment]
tests failure is not related to this commit.

**Comment by Swiip** [comment]
It's our shrinkwrap mechanism which prevent updating the dependencies.

Could you:
```
node test/template-cli deps
cd test/tmp/deps
rm -rf node_modules
npm install
npm shrinkwrap
cp npm-shrinkwrap.json ../..
```

And commit the file? We should definitely write doc about that... and make a script...

**Comment by e-oz** [comment]
I did it, tests are failed again because of dependencies.
Changes in this commit are pretty simple, easy to observe. Feel free to decline pr, my aim was just to warn you about critical changes in gulp-filter.

**Comment by Swiip** [comment]
This failure is actually a real one. You successed fixing the shrinkwrap thing but there is a use of gulp filter you miss: https://github.com/Swiip/generator-gulp-angular/blob/master/app/templates/gulp/_styles.js#L68

**Comment by e-oz** [comment]
Really, my fault, sorry.
Thanks for checking it.

**Comment by Swiip** [comment]
Yet another problem, doesn't understand this one...

**Pull request closed without merging**
