### PR TITLE
Fix bowerOverrides for bootstrap-sass-official

### LINKED ISSUE #644: Fonts Aren't Copied to Dist - Works on OSX But Not Linux Server
Not sure how to give the best information for this but the fonts files aren't being copied to the dist/fonts/ directory on my linux server. It is working fine on my OSX dev machine however.

OSX Output:

```
gulp build
[18:09:10] Using gulpfile xxx/gulpfile.js
[18:09:10] Starting 'scripts'...
[18:09:10] Starting 'styles'...
[18:09:11] Starting 'partials'...
[18:09:11] Starting 'fonts'...
[18:09:11] Starting 'other'...
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
[18:09:12] gulp-inject 45 files into index.less.
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
[18:09:14] Finished 'styles' after 3.49 s
[18:09:15] Finished 'fonts' after 3.77 s
[18:09:15] Time: 2182ms
   Asset   Size  Chunks             Chunk Names
index.js  68614       0  [emitted]  main
[18:09:15] Finished 'scripts' after 4.81 s
[18:09:15] Starting 'inject'...
[18:09:15] gulp-inject 1 files into index.html.
[18:09:15] gulp-inject 1 files into index.html.
[18:09:15] Finished 'inject' after 25 ms
[18:09:15] Finished 'partials' after 4.11 s
[18:09:15] Starting 'html'...
[18:09:15] gulp-inject 1 files into index.html.
[18:09:32] Finished 'other' after 21 s
[18:09:32] 'dist/' styles/app-bcef3035.css 53.9 kB
[18:09:32] 'dist/' scripts/app-a03cbc3f.js 48 kB
[18:09:32] 'dist/' styles/vendor-66762bbe.css 112.98 kB
[18:09:32] 'dist/' scripts/vendor-1d69d702.js 558.15 kB
[18:09:32] 'dist/' index.html 666 B
[18:09:32] 'dist/' all files 773.7 kB
[18:09:32] Finished 'html' after 17 s
[18:09:32] Starting 'build'...
[18:09:32] Finished 'build' after 11 μs
```

Linux Output:

```
gulp build
[23:08:02] Using gulpfile xxx/gulpfile.js
[23:08:02] Starting 'scripts'...
[23:08:03] Starting 'styles'...
[23:08:03] Starting 'partials'...
[23:08:03] Starting 'fonts'...
[23:08:04] Starting 'other'...
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
[23:08:07] gulp-inject 45 files into index.less.
[23:08:08] Finished 'fonts' after 4.12 s
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
[23:08:10] Finished 'styles' after 7.19 s
[23:08:13] Time: 6055ms
   Asset   Size  Chunks             Chunk Names
index.js  68614       0  [emitted]  main
[23:08:13] Finished 'scripts' after 11 s
[23:08:13] Starting 'inject'...
[23:08:13] gulp-inject 1 files into index.html.
[23:08:13] gulp-inject 1 files into index.html.
[23:08:13] Finished 'inject' after 49 ms
[23:08:13] Finished 'other' after 9.93 s
[23:08:13] Finished 'partials' after 10 s
[23:08:13] Starting 'html'...
[23:08:14] gulp-inject 1 files into index.html.
[23:08:44] 'dist/' styles/app-23ae5ead.css 54.48 kB
[23:08:44] 'dist/' styles/vendor-474244d3.css 118.12 kB
[23:08:44] 'dist/' scripts/app-7a22d7ec.js 48 kB
[23:08:44] 'dist/' scripts/vendor-f19aae87.js 568.87 kB
[23:08:44] 'dist/' index.html 666 B
[23:08:44] 'dist/' all files 790.13 kB
[23:08:44] Finished 'html' after 30 s
[23:08:44] Starting 'build'...
[23:08:44] Finished 'build' after 37 μs
```

In the end. OSX has a `dist/fonts/` directory and Linux doesn't.

### PR DESCRIPTION
**Pull request by Blind238**
should fix #644

### CODE REVIEW

**Comment by Swiip** [comment]
:+1:

**Comment by zckrs** [comment]
Tests should cover these cases

**Comment by Swiip** [comment]
Yep... forgot this. Why the coverage report didn't alert us?

**Comment by zckrs** [comment]
https://travis-ci.org/Swiip/generator-gulp-angular/jobs/72481607#L1091

Check config at https://coveralls.io/github/Swiip/generator-gulp-angularr/notifications/webhook

**Comment by zckrs** [comment]
Maybe the token is wrong

**Pull request merged**
