### PR TITLE
Release v1.0.0

### PR DESCRIPTION
**Pull request by zckrs**

### CODE REVIEW

**Comment by Swiip** [comment]
:tada: 1.0.0 :tada:

**Comment by Swiip** [comment]
go !

**Comment by intellix** [comment]
Tag!

**Comment by Swiip** [comment]
I run all the test twice first, but expect it today ;)

**Comment by Swiip** [comment]
done https://github.com/Swiip/generator-gulp-angular/releases/tag/v1.0.0 :)

**Pull request merged**
