### PR TITLE
TypeScript enhancements

### PR DESCRIPTION
**Pull request by Toilal**
This fix two issues in TypeScript support #247 & #246

TypeScript definitions file are now downloaded using [tsd](http://definitelytyped.org/tsd/).

`gulp tsd` also automatically fetch definitions files available for dependencies defined in bower.json, which is a feature missing from tsd.

TODO:
- [x] Use sortOutput to inject in right order (#247)
- [x] Use tsd to download definitions files (#246)
- [x] Use [tslint](https://www.npmjs.com/package/tslint)

### CODE REVIEW

**Comment by Swiip** [comment]
I was afraid by `gulp/tsd.js`. Have you seen https://www.npmjs.com/package/gulp-tsd ? It seems to do what you need.

**Comment by Toilal** [comment]
@Swiip You're right, it's really ugly, especially the npm install call from gulp ... I'll try to have a closer look at this gulp plugin, but it claims it support only install command, and I also need the init command.

I also wonder if it's really useful to install definitions files on each filechange, because it's relativelly slow ...

**Comment by Toilal** [comment]
gulp-tsd doesn't do what i wan't. It can only reinstall definition files from tsd.json, which should already has been initialized and loaded by `tsd init` and `tsd install <dependencies>` ... 

I think i'll fork gulp-tsd and implement more commands, or maybe just create a new `gulp-tsd-cli` that directly map available tsd commands ...

**Comment by Swiip** [comment]
I wonder at what point we should put what you're doing right now as a recipe and only support the addition of the preprocessor...

We have to produce something which work out of the box but don't hesitate to be "minimalist"

**Comment by Toilal** [comment]
I didn't know TypeScript before, but having those definition files based on bower dependencies is really mandatory to benefits of TypeScript features : better code assist in editor and type checking when using angularJS and any other supported dependency having its definition file available in TSD.

After more reflexion, i think I can avoid creating a new gulp plugin, and just use the `tsd` npm package directly in gulp `tsd.js` file. It should not be that complex, it would avoid doing the really dirty thing `npm install -g tsd` task, and will replace `exec` calls with proper API calls against `tsd` module.

**Comment by Toilal** [comment]
It's done @Swiip, I think it's ready now. I've also performed the merge of my 3 PRs ([available here](https://github.com/Toilal/generator-gulp-angular/tree/typescript-translate-merge)), and all seems OK after performing `npm test` and few manual tests.

**Comment by Swiip** [comment]
Don't understand, I test your code and it's failing. I chose all default options except for TypeScript.

It seams that the jQuery types generated doesn't compile. All details here: https://gist.github.com/Swiip/2c2c531340b3f86f2c2f

I tried to relaunch Travis on this one.

**Comment by Toilal** [comment]
Strange ... Same conclusion as you ... I'll give it a try in the afternoon.

**Comment by Toilal** [comment]
It seems the [JQuery Definition File](https://github.com/borisyankov/DefinitelyTyped/commits/master/jquery/jquery.d.ts) already use Union Types, which is a new feature available only in latest [TypeScript 1.4 version](http://blogs.msdn.com/b/typescript/archive/2015/01/16/announcing-typescript-1-4.aspx), released 3 days ago.

Only bumping the gulp-typescript to latest version fix the problem.

**Comment by Toilal** [comment]
Rebased and bump gulp-typescript to support latest typescript features.

**Comment by Swiip** [comment]
Let's hope there is no more joke on TypeScript update which break the build.

I feal that `gulp/tsd.js` should be a gulp plugin but I did some test with `gulp-tsd` and I'm not convinced so I think is the best right now.

I played a little with tsd.js and I've got a few questions:
- why bother with `tsd:init` if we deliver a tsd.json in the first place?
- can we move the generated files in `.tmp/typings`? I tried to change in the tsd.json but it doesn't work, it's override at each install.

**Comment by Toilal** [comment]
- why bother with tsd:init if we deliver a tsd.json in the first place?

It avoids maintaining this file.

- can we move the generated files in .tmp/typings? I tried to change in the tsd.json but it doesn't work, it's override at each install.

It would be possible if dropping tsd:init, and adding tsd.json manually with the generator, because tsd init doesn't support any options (there's a [TODO in tsd sources](https://github.com/DefinitelyTyped/tsd/blob/dev/next/src/tsd/API.ts#L55-L56))

So do you want to generate the tsd.json with yeoman instead of tsd init ? So we can change this directory ?

**Comment by Swiip** [comment]
I didn't see that we don't ship the tsd.json, ok like this.

A last question. When the tsd.json has been created, the init action seams to be avoided. But my changes in the tsd.json are still replaced on a `tsd:install`... Something about the install options?

**Comment by Toilal** [comment]
Yes, i just need to remove this line : https://github.com/Swiip/generator-gulp-angular/pull/250/files#diff-ede3eda71fe47daa7dfca48ba41656f5R35.

**Comment by Toilal** [comment]
Afterall, i think it's easier to just ship tsd.json like bower.json and package.json.

**Comment by Toilal** [comment]
Removing the `saveToConfig` disable writing of `typing/tsd.d.ts` ... So we can't do that ... It seems it's a weird API design issue ...

**Comment by Toilal** [comment]
There's another `saveBundle` that saves only `typing/tsd.d.ts`, so no problem, i'll do.

**Comment by Toilal** [comment]
No luck, parameters existing in tsd.json are not used ... grmlmlmlml

**Comment by Swiip** [comment]
tsd.json got some git hashcode inside, does this can't become obsolete?

All of this seams quite new. Perhaps we should just keep it like this and I think we'll see a `gulp-tsd` working on a single line in a few months

**Comment by Toilal** [comment]
I've opened an issue: https://github.com/DefinitelyTyped/tsd/issues/117. At the moment, i think we can't change this directory ...

**Comment by Toilal** [comment]
@Swiip Yes, with saveToConfig option, it won't add any dependencies and hashcode in tsd.json.

But I think we don't need them as we are using gulp to read dependencies from bower instead of command line tsd (which only read dependencies from tsd.json).

**Comment by Toilal** [comment]
@Swiip i'll make changes though ... but it won't work until tsd issue is fixed. I still think it's better not to overwrite tsd.json on each `gulp tsd:install` run.

**Comment by Toilal** [comment]
hoho, there's a `readConfig` method in tsd API ... maybe maybe ...

**Comment by Toilal** [comment]
It works with `readConfig` method.

**Comment by Toilal** [comment]
I'm not sure a `gulp-tsd` will really be more efficient. Main problem is that tsd API is still undocumented, so reading the source code is required ... That beeing said, it's well written, and TypeScript types really help reading the code.

But for now it works properly, and using `props.path.tmp` directory.

**Comment by Swiip** [comment]
I like the change, I merge this when Travis is ok

**Pull request merged**
