### PR TITLE
refacto index.js & format.js & add node tests

### PR DESCRIPTION
**Pull request by Swiip**
This is my undergoing refactoring of the node source files. My first idea of splitting files by options was not really doable, so I chose something less strict.

I started writing full node unit testing.

It's not finished:
- [x] Finish writing tests
- [x] Update method comments.

### CODE REVIEW

**Comment by zckrs** [comment]
:+1:

**Comment by Swiip** [comment]
Sorry for the blackout, I wanted to focus on this :)

**Comment by Swiip** [comment]
Done, and with comments!

[Coverage Status](https://coveralls.io/r/Swiip/generator-gulp-angular?branch=refacto-format)

**Comment by zckrs** [comment]
Awesome PR. :clap: :clap: :clap: 
Very nice work.

100% coverage :dancer: 

Each contributor should read and complete the suite test before open a PR. https://github.com/Swiip/generator-gulp-angular/tree/refacto-format/test/node

**Comment by Swiip** [comment]
Thanks ;)

**Pull request merged**
