### PR TITLE
Upgrade to Babel 6.x

### PR DESCRIPTION
**Pull request by scttcper**
Babel 6 requires es2015 preset package. Decided to use the babel-loader query string, could also use a .babel-rc file. https://github.com/babel/babel-loader#options

### CODE REVIEW

**Comment by Swiip** [comment]
Nice, can you rebase it ? (sorry for the huge delay)

**Comment by scttcper** [comment]
@Swiip rebased and tests are passing again.

**Comment by Swiip** [comment]
awesome!

**Comment by pablorsk** [comment]
Your work is awesome! 

`gulp serve` work fine, but `gulp dist` generate a project but don't work fine, console show this error:

```
Error: [$injector:strictdi] o is not using explicit annotation and cannot be invoked in strict mode
```

Any ideas?

**Comment by scttcper** [comment]
@pablorsk sounds like you're having issues with ngInject
Make sure you have ng-strict-di enabled and that you have 'ngInject' at the top of your controllers.

**Comment by pablorsk** [comment]
hi @scttcper!

I have ng-strict-di on <html> element. but with babel5 work all with `/** @ngInject */` before all function with injections. Need I add  `'ngInject'` on all files? My question is only becouse now with babel5 is working.

Regards...

**Comment by scttcper** [comment]
Depends what version of nginject you're using. Either way, that's where I would start looking for your issue.

Edit: or babel 6 broke the version of nginject you're using

**Pull request merged**
