### PR TITLE
Expand on per-environment build instructions

### PR DESCRIPTION
**Pull request by karlhorky**

### CODE REVIEW

**Comment by Swiip** [comment]
:+1:

**Comment by jtammen** [comment]
Hey, I think this recipe is very helpful.

I was just wondering whether it would make more sense to *not* put the generated config module into the sources folder. I am using this just to create environment specific build (think test, staging, production) of my app. And currently, I get a change in my sources ever time I run a build…

@karlhorky @Swiip What do you think?

**Comment by karlhorky** [comment]
@jtammen I usually ignore this file in `.gitignore` since it's a generated file.

**Comment by jtammen** [comment]
@karlhorky Sounds like a pragmatic solution, thanks! (-:

**Comment by cm325** [comment]
Hi,

I'm using this recipe:

https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/environment-specific-build.md

But the problem is that the constant file from the previous build is not removed automatically, when a new constant file (for a different enviroment) is created. Seems like that recipe should include a clean task, like:

`gulp.task('clean:config', function () {
  return del([path.join(conf.paths.src, '/app/properties.*.js')]);
});`

Also, instead of using configDev.json and config.json, I also opted for slightly different naming convention, like properties.dev.js, properties.test.js, etc-

**Pull request merged**
