### PR TITLE
directive's controller should be defined in outer scope

### PR DESCRIPTION
**Pull request by aksakalli**
According to Angular Style Guide by johnpapa, controller should be defined in outer scope [[style-y075](https://github.com/johnpapa/angular-styleguide#style-y075)]

### CODE REVIEW

**Comment by zckrs** [comment]
Where is the change ? I see only indentation edit

**Comment by Swiip** [comment]
I was looking at the same time. The difference is that the directive factory function is closed before and not after. I would say, why not.

**Comment by aksakalli** [comment]
I am using snippets, and it was different than my template. It is just a syntactic taste... And it is defined so in es6 as well.

**Comment by Swiip** [comment]
Can you rebase this ?

**Pull request closed without merging**
