### PR TITLE
Add npm test support using scripts in package.json

### PR DESCRIPTION
**Pull request by Toilal**
I think it's a good practice to make "npm test" execute all tests.

### CODE REVIEW

**Comment by zckrs** [comment]
:+1: for `npm test`

But `npm build` is a simple duplication of `gulp` and is not a shortcut.

**Comment by Toilal** [comment]
yes, i'll remove, useless :)

**Comment by Toilal** [comment]
I'm not sure protractor should be run with `npm test`, because it can't work on headless servers (requires chrome).

**Comment by zckrs** [comment]
TravisCI run `npm test` and we dont have a SauceLabs. Build will always failed. 

We cant merge this PR sorry :-/

**Comment by Toilal** [comment]
Won't we keep `gulp test` only ? Even if it's quite useless, i think it's still good practice to have a `npm test` command that just works, even if e2e tests are not executed with this command.

**Comment by zckrs** [comment]
Sorry I confused `npm test` of generator with generated app.

Yeah just keep `gulp test`. E2E tests are not yet adequate.

**Pull request merged**
