### PR TITLE
Remove "yo" to avoid unmet peer dependency

### LINKED ISSUE #872: False Positive Unmet Peer Dependency in npm 3
Trying to install this on OS X 10.11, Node 4.2.1, npm 3.3.9.
Here is the output:
```bash
 work_folder  》 npm install -g generator-gulp-angular
/usr/local/lib
├── generator-gulp-angular@1.0.0
└── UNMET PEER DEPENDENCY yo@>=1.0.0
npm WARN EPEERINVALID generator-gulp-angular@1.0.0 requires a peer of yo@>=1.0.0 but none was installed.
```
However...
```bash
 work_folder  》 npm list -g | grep yo
│ └─┬ yosay@1.0.5
└─┬ yo@1.4.8
  └─┬ yosay@1.0.5
```
As you can see, I do have `yo` installed at the proper version level, and there are no other unmet dependencies. I have also opened this issue with yo directly as this seems to also be occurring with other  generators that depend on yo as a peer.

### PR DESCRIPTION
**Pull request by zckrs**
fix #872

### CODE REVIEW

**Comment by damienstanton** [comment]
:+1: that was fast!

**Comment by Swiip** [comment]
:+1:

**Comment by vladimirich** [comment]
Can you tell me, how can I install this package from master using npm? npm install -g generator-gulp-angular still installs package with yo as peerDependency

**Comment by damienstanton** [comment]
@vladimirich It looks like you might need to pull the latest version. The peerdep has been removed from `package.json` as far as I can tell.

You can also always install from a local clone with `npm install -g path/to/generator-gulp-angular/`

**Comment by vladimirich** [comment]
@damienstanton ty for feedback!

**Pull request merged**
