### PR TITLE
[JS] Illustrate angular-styleguide by John Papa

### PR DESCRIPTION
**Pull request by zckrs**
In the same line of https://github.com/Swiip/generator-gulp-angular/pull/469, add a directive (malarkey) add a factory (githubAPI), add a constants.

:warning: don't merge before #469 is already merged

* [x] [Style [Y033](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y033)]
* [x] [Style [Y034](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y034)]
* [x] [Style [Y035](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y035)]
* [x] [Style [Y040](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y040)] 
* [x] [Style [Y050](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y050)]
* [x] [Style [Y051](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y051)]
* [x] [Style [Y052](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y052)]
* [x] [Style [Y053](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y053)]
* [x] [Style [Y060](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y060)]
* [x] [Style [Y061](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y061)]
* [x] [Style [Y070](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y070)]
* [x] [Style [Y072](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y072)]
* [x] [Style [Y073](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y073)]
* [x] [Style [Y074](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y074)]
* [x] [Style [Y075](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y075)]
* [x] [Style [Y076](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y076)]
* [x] [Style [Y080](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y080)]
* [x] [Style [Y125](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y125)]
* [x] [Style [Y126](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y126)]
* [x] [Style [Y128](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y128)]
* [x] [Style [Y129](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y129)]
* [x] [Style [Y170](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y170)]
* [x] [Style [Y171](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y171)]
* [x] [Style [Y180](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y180)]
* [x] [Style [Y181](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y181)]
* [x] [Style [Y210](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y210)]
* [x] [Style [Y211](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y211)]
* [x] [Style [Y212](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y212)]
* [x] [Style [Y240](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y240)]

### CODE REVIEW

**Comment by robertbaker** [comment]
Needs merged @Swiip

**Comment by zckrs** [comment]
No alaways work in progress

**Comment by zckrs** [comment]
ngInject + CoffeScript = pain

**Comment by Swiip** [comment]
Adding a directive and a service is great. But I'm not a big fan of putting contributors name in front.

As an alternative, I would suggest that we put the tech.json in the github sources and the project will request this file directly on github. I also imagine the malarkey directive about the tech list, the text should be in the jumbotron. We can even put a filter on the list of tech cards following what is typed in the malarkey.

About design, I would suggest to split up the code of the directive. The directive itself loads the data. I think the data should be given in parameter. If not, the directive is not reusable.

As a bonus, we can imagine getting the data from github with the ressource option the user choose ($http, $resource, restangular).

There is some `angular.forEach` in the code. My own guidelines are to use es5 Array.prototype.forEach now or did I miss another "official rules" :) ?

In TypeScript, and it will be the same for ES6. As we have the class concept and all the code is not anymore in the constructor, the `var vm = this` is not really usable anymore. I started to use some real `this` in TypeScript helped by the new `=>` operator.

Finally, I want to say that I'm really happy to have all these illustrations in the project but it also make me think that we shouldn't go any further. More code in the project will looks like a real project, not some example to remove. I also see that we are exactly doing the work for having subgenerators: having a model of each type of angular component written in the four languages. I don't say it's done, but part of the road will be done.

**Comment by zckrs** [comment]
Ready to merge :-)
Javascript, Coffee, ES6, Typescript, Bootstrap, Angular-Material, Foundation, CSS supported.
Javascript follow john papa style guide
I modify design of sample application to add 
* two directives
* two service
* toastr, moment, malarkey constant
* separate file for `.config()` `.run()` and router setup

74 files changed @Swiip take a minimum time to review before merge

I will update the parent PR #469

**Comment by robertbaker** [comment]
merge merge merge :)

**Comment by robertbaker** [comment]
Are the gulp files wrapped in an IFFE? I did that to my own proj and everything works.

**Comment by Swiip** [comment]
- controller specs : scope is never used
- love the acme as component prefix :)
- es6 : main controller should have methods, not functions defined in the constructor even if it breaks the vm = this principle, same as for typescript
- es6 : some more anonymous function could be replaced by a =>
- ts : should we define and export at the end of the file as for es6 & js ?

**Comment by zckrs** [comment]
- controller specs : scope is never used

=> Done
- es6 : main controller should have methods, not functions defined in the constructor even if it breaks the vm = this principle, same as for typescript

=> Done
- es6 : some more anonymous function could be replaced by a =>

=> Done

- ts : should we define and export at the end of the file as for es6 & js ?

=> I don't know what we should do :-/

**Comment by Swiip** [comment]
:+1: !!

**Pull request merged**
