### PR TITLE
UI frameworks fixes

### LINKED ISSUE #489: Customize Foundation
Hi,

i try to figure out how to customize the foundation styles.

As i know the way to do it is to change the parameters in _settings.scss

But changing this under "bower_components" does not make sense.

When i try to set a value in like index.css it does not effect the foundation appearance at all.

Am i missing something?

### LINKED ISSUE #492: Since #466, with Stylus,  sample app have no css
https://github.com/Swiip/generator-gulp-angular/pull/466

Because bower deps missing. 

We can use: 
* Bootstrap - Stylus: https://github.com/maxmx/bootstrap-stylus :warning: wrong main property in their bower.json
* Foundation - Less: not found
* Foundation - Stylus: not found

Maybe use CSS lib as fallback

### PR DESCRIPTION
**Pull request by Swiip**
- fix #492 foundation.css was excluded from wiredep for all css prepro but it had to be only for sass
- fix #489 illustration of customizings for bootstrap and foundation

### CODE REVIEW

**Comment by zckrs** [comment]
Can you fix issue for Stylus ?

**Comment by Swiip** [comment]
It's #492 no?

**Comment by zckrs** [comment]
Yep. But I didn't see how you fix case for Bootstrap + Stylus

**Comment by Swiip** [comment]
foundation.css is in the bower.json of foundation so it will be included if we don't exclude it.

we excluded foundation.css from wiredep for all css prepro which is wrong, I only changed that we keep this exclusion only for sass.

**Comment by Swiip** [comment]
Sorry for reading #492 badly. Go for bootstrap-stylus.

**Pull request merged**
