### PR TITLE
bump deps

### PR DESCRIPTION
**Pull request by stevemao**

### CODE REVIEW

**Comment by zckrs** [comment]
Thanks but we can't merge. 
In fact test build failed ([output log](https://travis-ci.org/Swiip/generator-gulp-angular/jobs/54669810#L1283))
I don't know why Travis return a success

**Comment by zckrs** [comment]
[yeoman-generator](https://github.com/yeoman/generator/blob/master/package.json#L54) don't support lodash3 at moment

**Comment by stevemao** [comment]
Not sure what causes the problem but this needs to be fixed

**Comment by zckrs** [comment]
Do you success to generate a project with bump deps ?

**Comment by stevemao** [comment]
No :disappointed:

**Comment by stevemao** [comment]
Had some time to investigate this. 

They have updated lodash https://github.com/yeoman/generator/blob/master/package.json#L54

However, you will need to import your own underscore.string https://github.com/yeoman/generator/commit/803d2cd487cb8f845b1c8284f62198f835a3d0ae

I will repush this once a they have made a new release.

reopening this for reference

**Comment by stevemao** [comment]
Also if Travis returns a success that means there is not enough coverage?

**Comment by Swiip** [comment]
Believe me, we've got a lot of tests :)

Our "inception" test runs the generator with several configuration, it fails now, don't know why it was green before...

**Comment by stevemao** [comment]
:+1:

**Comment by Swiip** [comment]
I close this in favor of #501

**Pull request closed without merging**
