### PR TITLE
Fixed browser-sync html5 mode routing

### PR DESCRIPTION
**Pull request by jamesbehr**
Gives better SPA support to BrowserSync with an added dependency.

### CODE REVIEW

**Comment by 18601673727** [comment]
Nice PR, we need this very much, could someone merge this?

**Comment by Swiip** [comment]
Seams great

**Comment by zckrs** [comment]
@jamesbehr You should fix test before merge

**Comment by jamesbehr** [comment]
@zckrs Fixed Travis build, but coverage still pending

**Comment by Swiip** [comment]
There was some issues with coverall, forget the warning, next builds will be ok.

**Comment by Swiip** [comment]
Thanks !

**Comment by jamesbehr** [comment]
No problem. This should fix #65 btw

**Comment by Swiip** [comment]
That's an old one, would be glad if I could close it. I want to check it though...

**Pull request merged**
