### PR TITLE
feat(livescript): add livescript support

### PR DESCRIPTION
**Pull request by chhsiao1981**
add livescript support:

1. jshintrc add boss:true and unused: false if using livescript

2. add dotTemplates in files.json

3. prompts.json and props add jsPreprocessor

4. replace .js to .ls if using livescript

5. use .pipe $.wrap "(function(){\n'use strict';\n<%%= contents %>\n})();" when using livescript

6. techs.json add livescript

7. add corresponding test and passed npm test

### CODE REVIEW

**Comment by chhsiao1981** [comment]
I just rebased with master. Also tested with gulp serve and gulp server:dist.

Let's see which .ls files can stay in the repository and which should not be merged for now.

**Comment by chhsiao1981** [comment]
I just rebased and simplified the files to be the same file structure as .coffee. Also tested with gulp serve.

**Comment by zckrs** [comment]
Hi @chhsiao1981

I am not sure your PR will be merged one day.
Because maintain too many JSpreprocessor in one generator is really hard and complexe.

Maybe you should create a new generator who use this generator.

Sorry. :disappointed:

**Comment by Swiip** [comment]
This is not easy for me, you work a lot for this. But supporting a language is a big charge for us and I don't see how we can support a not well established langage that we don't know.

I advise you to established your code as an other generator focused on LiveScript.

**Comment by chhsiao1981** [comment]
no problem at all.
I'll just follow the updates of this generator and build up the livescript version generator.

**Pull request closed without merging**
