### PR TITLE
fix haml markup , fix #325

### LINKED ISSUE #325: .pipe($.consolidate('hamljs')) throws an error
I always get this error:
`TypeError: Object #<Object> has no method 'hamljs'`
from markups.js line 15 the error is thrown on line 17. 

The $.consolidate function looks like this 
`module.exports = function (engine, data, options) {
	"use strict";

	options = options || {};

	if (!engine) {
		throw new Error("gulp-consolidate: No template engine supplied");
	}

	try {
		if (engine === "hogan") {
			require("hogan.js");
		} else {
			require(engine);
		}
	} catch (e) {
		throw new Error("gulp-consolidate: The template engine \"" + engine + "\" was not found. " +
			"Did you forget to install it?\n\n    npm install --save-dev " + engine);
	}`

there is a node module in the node_modules folder:
hamljs

I also tried to reinstall.

### PR DESCRIPTION
**Pull request by Swiip**
With consolidate, it was "haml" and not "hamljs" to use.

### CODE REVIEW

**Comment by tb** [comment]
@Swiip haml did not work for me on main.haml, I checked https://github.com/tj/consolidate.js#supported-template-engines and tried with https://github.com/9elements/haml-coffee and it worked.

**Comment by Swiip** [comment]
`hamljs` was not working but I successfully compiled a haml template with consolidate with `haml` as key.

**Comment by tb** [comment]
@Swiip nm, I checked with haml again now and its working fine

**Comment by guiiruiz** [comment]
Just "haml" isn't working for me.
When I try to run "gulp serve" it's trying to use "hamljs" and I'm getting this error:

    Error: Cannot find module 'hamljs'
      at Function.Module._resolveFilename (module.js:338:15)
      at Function.Module._load (module.js:280:25)
      at Module.require (module.js:364:17)
      at require (module.js:380:17)
      at Function.exports.haml.render (/var/www/test/node_modules/gulp-consolidate/node_modules/consolidate/lib/consolidate.js:386:54)
      at /var/www/test/node_modules/gulp-consolidate/node_modules/consolidate/lib/consolidate.js:146:25
      at /var/www/test/node_modules/gulp-consolidate/node_modules/consolidate/lib/consolidate.js:99:5
      at fs.js:272:14
      at /var/www/test/node_modules/karma/node_modules/graceful-fs/graceful-fs.js:104:5
      at /var/www/test/node_modules/wiredep/node_modules/bower-config/node_modules/graceful-fs/graceful-fs.js:104:5
      at Object.oncomplete (fs.js:108:15)

Versions:
generator-gulp-angular@0.11.0
gulp-consolidate@0.1.2
haml@0.4.3

**Comment by guiiruiz** [comment]
I was getting the error below when trying to "gulp serve"

    Error: Cannot find module 'hamljs'
     ...

After a long time I realize that the problem was in the file:

    /node_modules/gulp-consolidate/lib/consolidate.js

To fix that I just changed this line from:


    386   var engine = requires.hamljs || (requires.hamljs = require('hamljs'));
    
To:

     386   var engine = requires.haml || (requires.haml = require('haml'));

**Pull request merged**
